# Generated by Django 3.2.9 on 2021-11-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('thumbnailUrl', models.URLField()),
                ('album', models.CharField(max_length=100)),
                ('authorFirstName', models.CharField(max_length=50)),
                ('authorLastName', models.CharField(max_length=50)),
                ('authorUserName', models.CharField(max_length=50)),
            ],
        ),
    ]
